### ISSUE TITLE
error with garbage cube

### ISSUE THREAD

**Issue by DieDana** [DeadByte42/Raft-WhereIsMyDishes#1]
First sorry for my bad english.
In single player and multiplayer we have the problem that an error appears when taking a garbage cube. If we deactivate the mod we have no error.
![Log](https://user-images.githubusercontent.com/108569244/176992218-0882dbcd-9a8e-415d-85eb-6ffab79fba86.jpg)

**Comment by DeadByte42** [comment]
Which version of the mod? If you has 1.0 version, modloader don't check updates. Latest on raftmodding.com is 1.0.2 without that issue

**Comment by DieDana** [comment]
I have version 1.0
I look after an update of the mod if the error is still there.

**Comment by DieDana** [comment]
Thanks It works now. It was my fault....
