### ISSUE TITLE
Cooking pot not working

### ISSUE THREAD

**Issue by git4o** [DeadByte42/Raft-WhereIsMyDishes#2]
Hi, I was trying to use the cooking pot and when I installed the mod and it kept saying (only when I put stuff in the cooking pot) when I wanted to start it said: "an error occurred"! I attached what it said in the console and my mod list. (This issue only started when I installed where is my dishes)

Error:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/71034923/177827153-1761fd47-f6df-4f5c-8c8b-47e8f2c5f11b.png">
Mods:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/71034923/177827360-c3803314-f804-4d7f-9252-83e727b02625.png">

**Comment by DeadByte42** [comment]
Update the RML to newest version, it's should fix this error

**Comment by git4o** [comment]
Thanks a lot! It works now! TY! <3
