### ISSUE TITLE
Installing without mod manager?

### ISSUE THREAD

**Issue by TheOddler** [DeadByte42/Raft-WhereIsMyDishes#3]
Is there a way to install this without the mod manager? I'm on Linux and the mod manager won't work, and all other mods I'm using with a friend only need it installed on the server, he is on Windows so he is hosting which works fine. Though while he's not eating his bowls, I do.

**Comment by DeadByte42** [comment]
Hello. Sorry for late response. As far as I remember, there was some other mod loader for Raft (Unity loader, or something similar). I don't know if it's available on Linux. If you are a little familiar with c#, or at least with programming in general, you can convert the code from my mod to another loader (or ask in the discussion of the loader on the forum / in Discord). I do not forbid the use of my code.

**Comment by TheOddler** [comment]
Cool thanks! I am familiar with C#, so I might look into that. Thanks!
